---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
      - image: node:7.4.0
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: ~/cci-demo-rails-webpacker-ng-cli
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential nodejs
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rake test
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: NPM Test
          command: yarn test
      - run:
          name: NPM Lint
          command: yarn run lint