---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: ~/cci-rails-webpacker-ng-cli
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential nodejs
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rake test
      - run:
          name: Run Specs
          command: bundle exec rake spec
      - run:
          name: Install Dependencies
          command: bin/yarn install
      - run:
          name: NPM Test
          command: bin/yarn test
      - run:
          name: NPM Lint
          command: bin/yarn run lint