version: 2
jobs:
  build:
    docker:
      - image: node:7.6.0
    working_directory: ~/cci-demo-rails-webpacker-ng-cli
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
      - run:
          name: NPM Lint
          command: npm lint
