---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root
      - image: node:7.4.0
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: ~/cci-demo-rails-webpacker-ng-cli
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential nodejs
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: DB Migrations
          command: bundle exec rake db:migrate
      - run:
          name: Run Tests
          command: bundle exec rake test
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
      - run:
          name: NPM Lint
          command: npm run lint