---
version: 2
jobs:
  build:
    docker:
      - image: node:7.6.0
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: ~/cci-demo-rails-webpacker-ng-cli
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM Test
          command: npm test
      - run:
          name: NPM Lint
          command: npm run lint
